import Head from "next/head";
import { Profile } from "@/components/scene/Profile";
import { Carrier } from "@/components/scene/Carrier";
import { grantsAwards, soloExhibitions } from "@/public/carrierContents";
import { SceneManager } from "@/components/SceneManager";
import Layout from "../components/Layout";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <SceneManager
          scenes={[
            <Profile key="scene-profile" />,
            <Carrier
              key="scene-awards"
              items={grantsAwards}
              title="Grants and Awards"
            />,
            <Carrier
              key="scene-exhibitions"
              items={soloExhibitions}
              title="Solo Exhibitions"
            />,
          ]}
          languageMode={"ja"}
        />
      </Layout>
    </>
  );
}
