"use client";

import { ThemeProvider } from "@/components/ThemeProvider";
import "./styles/globals.css";
import { useRef, useState } from "react";
import { FontTester } from "@/components/FontTester";
import { HambergerMenu } from "@/components/HambergerMenu";

// export const metadata = {
//   title: "morita asuka",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [jaIndex, setJaIndex] = useState<number>(0);
  const [enIndex, setEnIndex] = useState<number>(0);
  const jaFontRef = useRef<HTMLParagraphElement>(null);
  const enFontRef = useRef<HTMLParagraphElement>(null);

  return (
    <html>
      <body>
        <ThemeProvider>
          <FontTester
            jaIndex={jaIndex}
            enIndex={enIndex}
            jaFontRef={jaFontRef}
            enFontRef={enFontRef}
          >
            <HambergerMenu
              setJaIndex={setJaIndex}
              setEnIndex={setEnIndex}
              jaFontRef={jaFontRef}
              enFontRef={enFontRef}
            />
            {children}
          </FontTester>
        </ThemeProvider>
      </body>
    </html>
  );
}
