import Head from "next/head";
import { Inter } from "next/font/google";
import { FadeInElement } from "@/components/FadeInElement";
import { Profile } from "@/components/scene/Profile";
import { Carieer } from "@/components/scene/Carieer";
import { useState } from "react";
import { SceneManager } from "@/components/SceneManager";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // ぼかし強度 (stdDeviation) を state 管理する
  const [scene, setScene] = useState<number>(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <SceneManager scene={scene} />
        <p
          onClick={() => {
            setScene((scene + 1) % 2);
          }}
          style={{
            position: "fixed",
            bottom: "2rem",
            right: "3rem",
            color: "white",
          }}
        >
          →
        </p>
      </main>
    </>
  );
}
