import Head from "next/head";
import { useState } from "react";
import { SceneManager } from "@/components/SceneManager";

export default function Home() {
  // ぼかし強度 (stdDeviation) を state 管理する
  const [scene, setScene] = useState<number>(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <SceneManager scene={scene} />
        <p
          onClick={() => {
            setScene((scene + 1) % 3);
          }}
          className="arrow"
        >
          →
        </p>
      </main>
      <style jsx>{`
        .arrow {
          width: 2.5rem;
          background-color: white;
          text-align: center;
          line-height: 2.5rem;
          height: 2.5rem;
          border-radius: 50%;
          border: 1px solid white;
          position: fixed;
          bottom: 2rem;
          right: 5vw;
          color: black;
        }
      `}</style>
    </>
  );
}
