name: Deploy CMS Updates

# 「手動実行」をトリガーとする
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # CMSの最新データをビルド時にフェッチし、SSGで静的ファイルに反映させる
      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          production: true
          # 必要なら project-id: や org-id: の指定も
          # project-id: <YOUR_VERCEL_PROJECT_ID>
          # org-id: <YOUR_VERCEL_ORG_ID>
